//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knitwear
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knitwears_Main
    {
        public int Knitwears_Main_id { get; set; }
        public Nullable<int> Knitwears_Stock_id { get; set; }
        public Nullable<int> Knitwears_Plan_id { get; set; }
        public Nullable<int> Knitwears_Order_id { get; set; }
        public Nullable<int> Knitwears_Product_id { get; set; }
    
        public virtual Knitwears_Order Knitwears_Order { get; set; }
        public virtual Knitwears_Plan_Main Knitwears_Plan_Main { get; set; }
        public virtual Knitwears_Product Knitwears_Product { get; set; }
        public virtual Knitwears_Stock Knitwears_Stock { get; set; }
    }
}
