//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knitwear
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knitwears_Plan_Day
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knitwears_Plan_Day()
        {
            this.Knitwears_Plan_Main = new HashSet<Knitwears_Plan_Main>();
        }
    
        public int Knitwears_Plan_Day_id { get; set; }
        public string Knitwears_Plan_Day_Nomenclature { get; set; }
        public string Knitwears_Plan_Day_Date { get; set; }
        public string Knitwears_Plan_Day_Volume { get; set; }
        public string Knitwears_Plan_Day_Note { get; set; }
        public string Knitwears_Plan_Day_Status { get; set; }

        public string Nomenclature
        {
            get
            {
                return "Номенклатура: " + this.Knitwears_Plan_Day_Nomenclature;
            }
        }

        public string Date
        {
            get
            {
                return "Выполнить до: " + this.Knitwears_Plan_Day_Date;
            }
        }

        public string Status
        {
            get
            {
                return "Статус выполнения: " + this.Knitwears_Plan_Day_Status;
            }
        }

        public string Volume
        {
            get
            {
                return "Обьем: " + this.Knitwears_Plan_Day_Volume;
            }
        }
        public string Note
        {
            get
            {
                return "Примечание: " + this.Knitwears_Plan_Day_Note;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knitwears_Plan_Main> Knitwears_Plan_Main { get; set; }
    }
}
