//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knitwear
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knitwears_Plan_Main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knitwears_Plan_Main()
        {
            this.Knitwears_Main = new HashSet<Knitwears_Main>();
        }
    
        public int Knitwears_Plan_id { get; set; }
        public Nullable<int> Knitwears_Plan_Day_id { get; set; }
        public Nullable<int> Knitwears_Plan_Week_id { get; set; }
        public Nullable<int> Knitwears_Plan_Month_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knitwears_Main> Knitwears_Main { get; set; }
        public virtual Knitwears_Plan_Day Knitwears_Plan_Day { get; set; }
        public virtual Knitwears_Plan_Month Knitwears_Plan_Month { get; set; }
        public virtual Knitwears_Plan_Week Knitwears_Plan_Week { get; set; }
    }
}
