//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knitwear
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knitwears_Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knitwears_Recipe()
        {
            this.Knitwears_Main = new HashSet<Knitwears_Main>();
        }
    
        public int Knitwears_Recipe_id { get; set; }
        public string Knitwears_Recipe_Name { get; set; }
        public string Knitwears_Recipe_Ingredients_One { get; set; }
        public string Knitwears_Recipe_Ingredients_Two { get; set; }
        public string Knitwears_Recipe_Ingredients_Three { get; set; }
        public string Knitwears_Recipe_Ingredients_Four { get; set; }

        public string Name
        {
            get
            {
                return "Наименование: " + this.Knitwears_Recipe_Name;
            }
        }
        public string One
        {
            get
            {
                return "Сахар (кг): " + this.Knitwears_Recipe_Ingredients_One;
            }
        }
        public string Two
        {
            get
            {
                return "Вода (л): " + this.Knitwears_Recipe_Ingredients_Two;
            }
        }
        public string Three
        {
            get
            {
                return "Патока (кг): " + this.Knitwears_Recipe_Ingredients_Three;
            }
        }
        public string Four
        {
            get
            {
                return "Ароматизатор (кг): " + this.Knitwears_Recipe_Ingredients_Four;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knitwears_Main> Knitwears_Main { get; set; }
    }
}
